backend:
  name: github
  repo: animaplays/animaplays.github.io
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "animes"
    label: "Animes"
    folder: "static/content/animes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título do Anime", name: "title", widget: "string"}
      - {label: "Capa / Pôster", name: "image", widget: "image"}
      - {label: "Informações (Ex: T1 EP.1 • Legendado)", name: "subtitle", widget: "string"}
      - {label: "Descrição", name: "description", widget: "text", required: false}
